### ISSUE TITLE
iframe not working

### ISSUE THREAD

**Issue by Ziakimbogo** [hooshmang/recaptcha-bypass#1]
Traceback (most recent call last):
  File "C:\Users\chain\Downloads\recaptcha-bypass-main\recaptcha-bypass-main\example.py", line 11, in <module>
    solve_recaptcha(driver)
  File "C:\Users\chain\Downloads\recaptcha-bypass-main\recaptcha-bypass-main\recaptcha_bypass.py", line 274, in solve_recaptcha
    go_to_recaptcha_iframe2(driver)
  File "C:\Users\chain\Downloads\recaptcha-bypass-main\recaptcha-bypass-main\recaptcha_bypass.py", line 29, in go_to_recaptcha_iframe2
    recaptcha_iframe2 = WebDriverWait(driver=driver, timeout=10).until(
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\chain\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\support\wait.py", line 95, in until
    raise TimeoutException(message, screen, stacktrace)

**Comment by mahdi-marjani** [comment]
> Traceback (most recent call last): File "C:\Users\chain\Downloads\recaptcha-bypass-main\recaptcha-bypass-main\example.py", line 11, in solve_recaptcha(driver) File "C:\Users\chain\Downloads\recaptcha-bypass-main\recaptcha-bypass-main\recaptcha_bypass.py", line 274, in solve_recaptcha go_to_recaptcha_iframe2(driver) File "C:\Users\chain\Downloads\recaptcha-bypass-main\recaptcha-bypass-main\recaptcha_bypass.py", line 29, in go_to_recaptcha_iframe2 recaptcha_iframe2 = WebDriverWait(driver=driver, timeout=10).until( ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "C:\Users\chain\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\support\wait.py", line 95, in until raise TimeoutException(message, screen, stacktrace)

Please change the language of the web driver to English.
options.add_argument('--lang=en')

**Comment by mahdi-marjani** [comment]
So, changing the webdriver language to English will solve the problem

**Comment by Ziakimbogo** [comment]
yes , thanks
